apiVersion: apps/v1
kind: Deployment
metadata:
  name: copro-dislikes
  namespace: coprophage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coprophage
  template:
    metadata:
      labels:
        app: coprophage
    spec:
      containers:
      - name: coprophage-dislikes
        image: coprophage:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_TOPIC
          value: cdc_events.public.disliked_songs
