apiVersion: batch/v1
kind: CronJob
metadata:
  name: outpay
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: outpay
            image: outpay:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure

