apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: crabifyschrabify
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: crabify
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        hostPath:
          path: /Users/aldo/UPT/DataEng/crabify/postgres/.pgdata
          type: DirectoryOrCreate

